# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tablero', '0004_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministradorUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Unidad', unique=True)),
            ],
            options={
                'verbose_name': 'Administrador de Unidad',
                'verbose_name_plural': 'Administradores de Unidad',
            },
        ),
    ]
