# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0006_auto_20160506_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('hexadecimal', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Semaforo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.FloatField(default=0)),
                ('hasta', models.FloatField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Color')),
            ],
        ),
    ]
