# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0008_auto_20160510_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablero.Unidad'),
        ),
    ]
