# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0013_aperturaindicador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperturaindicador',
            name='apertura',
        ),
    ]
