# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 19:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0014_remove_aperturaindicador_apertura'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AperturaIndicador',
            new_name='TipoAperturaIndicador',
        ),
    ]
