# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0015_auto_20160513_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoaperturaindicador',
            options={'verbose_name': 'Tipo de Apertura por Indicador', 'verbose_name_plural': 'Tipos de Aperturas por Indicador'},
        ),
        migrations.RenameField(
            model_name='tipoaperturaindicador',
            old_name='titulo_apertura',
            new_name='apertura',
        ),
    ]
