# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0016_auto_20160513_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.FloatField(default=0)),
                ('resultado', models.FloatField(default=0)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.TipoAperturaIndicador')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Periodo')),
            ],
        ),
    ]
