# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0017_resultadoindicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalIndicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.FloatField(default=0)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.IndicadorObjetivo')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Periodo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='resultadoindicador',
            options={'verbose_name_plural': 'Resultado indicadores'},
        ),
    ]
