# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0020_auto_20160518_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.AlterModelOptions(
            name='totalindicador',
            options={'verbose_name_plural': 'Total indicadores'},
        ),
    ]
