# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0021_auto_20160524_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=150)),
                ('meta', models.FloatField(blank=True, default=0, null=True)),
                ('evaluacion', models.FloatField(blank=True, default=0, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablero.Proyecto')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablero.Status')),
            ],
            options={
                'verbose_name_plural': 'KPI',
            },
        ),
    ]
