# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-31 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0024_escala_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='meta',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
